export const Topic = [
  { name: 'Accessibility', value: 'Accessibility' },
  { name: 'Android', value: 'Android' },
  { name: 'Animation', value: 'Animation' },
  { name: 'Apps', value: 'Apps' },
  { name: 'CSS', value: 'CSS' },
  { name: 'Design', value: 'Design' },
  { name: 'Design Patterns', value: 'Design Patterns' },
  { name: 'Design Systems', value: 'Design Systems' },
  { name: 'E - Commerce', value: 'E - Commerce' },
  { name: 'Freebies', value: 'Freebies' },
  { name: 'Graphics', value: 'Graphics' },
  { name: 'HTML', value: 'HTML' },
  { name: 'Illustrator', value: 'Illustrator' },
  { name: 'Inspiration', value: 'Inspiration' },
  { name: 'iOS', value: 'iOS' },
  { name: 'JavaScript', value: 'JavaScript' },
  { name: 'Mobile', value: 'Mobile' },
  { name: 'Pattern ', value: 'Pattern ' },
  { name: 'Libraries', value: 'Libraries' },
  { name: 'Performance', value: 'Performance' },
  { name: 'Photoshop', value: 'Photoshop' },
  { name: 'Plugins', value: 'Plugins' },
  { name: 'React', value: 'React' },
  { name: 'Responsive ', value: 'Responsive ' },
  { name: 'Web', value: 'Web' },
  { name: 'DesignService ', value: 'DesignService ' },
  { name: 'Workers', value: 'Workers' },
  { name: 'SketchTypographyU', value: 'SketchTypographyU' },
  { name: 'IUsabilityUser', value: 'IUsabilityUser' },
  { name: 'ExperienceWallpapersWeb ', value: 'ExperienceWallpapersWeb ' },
  { name: 'DesignWordPressWorkflow', value: 'DesignWordPressWorkflow' }
]
